baseURL = 'https://renz0kuken.github.io/outerhaven.github.io/'
languageCode = 'pt'
defaultContentLanguage = 'pt'
title = 'Outerhaven'
theme = "ananke"
SectionPagesMenu = "main"
disqusShortname = "outerhaven-1"
enableEmoji = true



[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[params.ananke.social.follow]
networks = [
  "bluesky",
]

[params.ananke.social.bluesky]
username = "jarbaspsf.bsky.social"
